import { app } from 'electron'

export interface ReportIssue {
  sheet_name?: string
  cell_address?: string
  severity?: string
  message?: string
  suggestion?: string
}

export function generateReport(issues: ReportIssue[], fileName: string): string {
  const errorCount = issues.filter(i => i.severity === 'high').length
  const warningCount = issues.filter(i => i.severity === 'medium').length
  const infoCount = issues.filter(i => i.severity === 'low').length
  const generatedAt = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, ' UTC')

  const severityColors: Record<string, string> = {
    high: '#e74c3c',
    medium: '#f39c12',
    low: '#3498db'
  }
  const severityLabels: Record<string, string> = {
    high: 'Error',
    medium: 'Warning',
    low: 'Info'
  }

  let rowsHtml = ''
  for (const i of issues) {
    const sev = i.severity || 'low'
    const color = severityColors[sev] || '#3498db'
    const label = severityLabels[sev] || 'Info'
    rowsHtml += `<tr>`
      + `<td>${escapeHtml(i.sheet_name || '')}</td>`
      + `<td><code>${escapeHtml(i.cell_address || '')}</code></td>`
      + `<td><span style="color:${color};font-weight:bold">${label}</span></td>`
      + `<td>${escapeHtml(i.message || '')}</td>`
      + `<td>${escapeHtml(i.suggestion || '')}</td>`
      + `</tr>`
  }

  return (
    '<!DOCTYPE html><html><head><meta charset="utf-8">'
    + '<title>CellSentry Report</title>'
    + '<style>'
    + 'body{font-family:system-ui,sans-serif;max-width:960px;margin:0 auto;padding:20px}'
    + 'h1{color:#2c3e50}table{border-collapse:collapse;width:100%}'
    + 'th,td{border:1px solid #ddd;padding:8px;text-align:left}'
    + 'th{background:#f8f9fa}.summary{display:flex;gap:20px;margin:16px 0}'
    + '.stat{padding:12px 20px;border-radius:8px;color:#fff;font-weight:bold}'
    + '</style></head><body>'
    + `<h1>CellSentry Report</h1>`
    + `<p><strong>File:</strong> ${escapeHtml(fileName)} | `
    + `<strong>Generated:</strong> ${generatedAt}</p>`
    + `<div class="summary">`
    + `<div class="stat" style="background:#e74c3c">Errors: ${errorCount}</div>`
    + `<div class="stat" style="background:#f39c12">Warnings: ${warningCount}</div>`
    + `<div class="stat" style="background:#3498db">Info: ${infoCount}</div>`
    + `</div>`
    + `<table><thead><tr>`
    + `<th>Sheet</th><th>Cell</th><th>Severity</th><th>Issue</th><th>Suggestion</th>`
    + `</tr></thead><tbody>${rowsHtml}</tbody></table>`
    + `<p style="color:#999;margin-top:20px">Generated by CellSentry v${app.getVersion()}</p>`
    + '</body></html>'
  )
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
